version: '3.3'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=diary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/postgres_data
  
  pgandmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=edwinegq@outlook.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - 5050:80
